[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"

[context.production.environment]
  MONGODB_URI = "mongodb+srv://n4k_user:7BgIIyjXuE78ScRC@cluster0.ehGufGu.mongodb.net/n4k_db?retryWrites=true&w=majority&appName=Cluster0"

# Redirecciones para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Manejo de 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
